package com.maijia.model;

import java.math.BigDecimal;
import java.util.Date;

public class UserProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.projectid
     *
     * @mbggenerated
     */
    private String projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.benmoney
     *
     * @mbggenerated
     */
    private BigDecimal benmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_project.currentmoney
     *
     * @mbggenerated
     */
    private String currentmoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.userid
     *
     * @return the value of user_project.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.userid
     *
     * @param userid the value for user_project.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.projectid
     *
     * @return the value of user_project.projectid
     *
     * @mbggenerated
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.projectid
     *
     * @param projectid the value for user_project.projectid
     *
     * @mbggenerated
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.benmoney
     *
     * @return the value of user_project.benmoney
     *
     * @mbggenerated
     */
    public BigDecimal getBenmoney() {
        return benmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.benmoney
     *
     * @param benmoney the value for user_project.benmoney
     *
     * @mbggenerated
     */
    public void setBenmoney(BigDecimal benmoney) {
        this.benmoney = benmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.status
     *
     * @return the value of user_project.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.status
     *
     * @param status the value for user_project.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.createtime
     *
     * @return the value of user_project.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.createtime
     *
     * @param createtime the value for user_project.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.mark
     *
     * @return the value of user_project.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.mark
     *
     * @param mark the value for user_project.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.currentmoney
     *
     * @return the value of user_project.currentmoney
     *
     * @mbggenerated
     */
    public String getCurrentmoney() {
        return currentmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.currentmoney
     *
     * @param currentmoney the value for user_project.currentmoney
     *
     * @mbggenerated
     */
    public void setCurrentmoney(String currentmoney) {
        this.currentmoney = currentmoney == null ? null : currentmoney.trim();
    }
}