package com.maijia.model;

public class UserAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.totalmoney
     *
     * @mbggenerated
     */
    private Double totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.waitrate
     *
     * @mbggenerated
     */
    private Double waitrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.principal
     *
     * @mbggenerated
     */
    private Double principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.frozen
     *
     * @mbggenerated
     */
    private Double frozen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.id
     *
     * @return the value of useraccount.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.id
     *
     * @param id the value for useraccount.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.totalmoney
     *
     * @return the value of useraccount.totalmoney
     *
     * @mbggenerated
     */
    public Double getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.totalmoney
     *
     * @param totalmoney the value for useraccount.totalmoney
     *
     * @mbggenerated
     */
    public void setTotalmoney(Double totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.waitrate
     *
     * @return the value of useraccount.waitrate
     *
     * @mbggenerated
     */
    public Double getWaitrate() {
        return waitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.waitrate
     *
     * @param waitrate the value for useraccount.waitrate
     *
     * @mbggenerated
     */
    public void setWaitrate(Double waitrate) {
        this.waitrate = waitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.principal
     *
     * @return the value of useraccount.principal
     *
     * @mbggenerated
     */
    public Double getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.principal
     *
     * @param principal the value for useraccount.principal
     *
     * @mbggenerated
     */
    public void setPrincipal(Double principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.frozen
     *
     * @return the value of useraccount.frozen
     *
     * @mbggenerated
     */
    public Double getFrozen() {
        return frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.frozen
     *
     * @param frozen the value for useraccount.frozen
     *
     * @mbggenerated
     */
    public void setFrozen(Double frozen) {
        this.frozen = frozen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.mark
     *
     * @return the value of useraccount.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.mark
     *
     * @param mark the value for useraccount.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}