package com.maijia.dao.account;

import com.maijia.model.UAccount;

public interface UAccountMapper {
	
	UAccount selectUserId(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated
     */
    int insert(UAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated
     */
    int insertSelective(UAccount record);
}