package com.maijia.dao.account;

import com.maijia.model.UserAccount;

public interface UserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbggenerated
     */
    int insert(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbggenerated
     */
    int insertSelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbggenerated
     */
    UserAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAccount record);
}