package com.maijia.dao.account;

import java.util.List;

import com.maijia.model.UserProject;

public interface UserProjectMapper {
	
	List<UserProject> selectUserProject(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbggenerated
     */
    int insert(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbggenerated
     */
    int insertSelective(UserProject record);
}